version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: bd10e231f9746d0920c2c6ddae0b662363c8720ff89cab5684f2b5241421aa8c

    docker:
      - image: circleci/python:3.7.1
        environment:
          PGHOST: 127.0.0.1
          PGUSER: voxsql
          PGPASS: voxsql
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: voxsql
          POSTGRES_DB: voxsql

    steps:

      - checkout

      - run:
          name: Download CodeClimate Test Reporter Binary
          command: |
            wget -O cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
            chmod +x ./cc-test-reporter

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.dev.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            ./cc-test-reporter before-build
            pytest --junit-xml=test-results/pytest/results.xml --cov-report=xml
            ./cc-test-reporter after-build --coverage-input-type coverage.py --exit-code $?

      - store_test_results:
          path: test-results
