version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
        environment:
          PGHOST: 127.0.0.1
          PGUSER: voxsql
          PGPASS: voxsql
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: voxsql
          POSTGRES_DB: voxsql

    steps:

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.dev.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest --junit-xml=test-results/pytest/results.xml

      - store_test_results:
          path: test-results
